### ISSUE TITLE
vertical orange line in code area

### ISSUE THREAD

**Issue by Byoung730** [angela-d/ghoulish-ui#1]
How do i remove it?  It's 80 spaces from the left...it is somehow connected to my linter?

I love this UI tho!!

**Comment by angela-d** [comment]
This is coming from the Wrap Guide package, if you don't want it, simply disable it by going to:

Edit > Preferences > Packages > search "wrap" and disable.

Glad you like the theme! :smiley:

**Comment by Byoung730** [comment]
Thanks!!

**Comment by angela-d** [comment]
No problemo!
