### ISSUE TITLE
Background image not showing through 

### ISSUE THREAD

**Issue by LucasGeos** [angela-d/ghoulish-ui#3]
Shows through behind tree view and the bar at the bottom of the window but not behind the code.

**Comment by angela-d** [comment]
Did you set the path incorrectly?

If you didn't put the image in the `/home/yourusername/.atom/packages/ghoulish-ui/imgs` folder, you'll want to specify the absolute path to the image.

For example, my current background is in my home directory, so I set my path as `/home/angela/deviantart.png` to the image.

(If you're on Windows or Mac, your paths will vary, but Finder / File Explorer should list the absolute path in the URL bar.)

![themepath](https://user-images.githubusercontent.com/33108490/62089201-b3b88e80-b22d-11e9-93cb-ef1171be05e0.png)

Full background:
![background](https://user-images.githubusercontent.com/33108490/62089358-41947980-b22e-11e9-9f55-0c086bd8ac00.png)

**Comment by LucasGeos** [comment]
Yep the path is specified in Settings in both ''Background Image" and "Tree View Background Image"

**Comment by LucasGeos** [comment]
mac 10.14.6 btw

**Comment by LucasGeos** [comment]
Probably something weird to do with running Atom on 10.14.6 rather than anything to do with your code!

**Comment by angela-d** [comment]
Did it stop working once you upgraded to 10.14.6?

> Yep the path is specified in Settings in both ''Background Image" and "Tree View Background Image"

The tree view works and is the same image as used for the background image option? 

 Make sure there isn't any whitespace that was accidentally added - that could potentially cause an undetectable difference to the naked eye.

If I get a chance tomorrow, I will test on a Mac running 10.14.6 and see if I can reproduce it on my end.

**Comment by LucasGeos** [comment]
Oh, fixed. Same image but the way it scaled it just gave flat black behind the code. Sorry!

I actually used a different theme before that really did break with 10.14.6, hence finding yours. Really like it, thanks!

**Comment by angela-d** [comment]
Very interesting!

I guess I never tested the theme with a smaller image, I always use wallpaper for the backgrounds when I swap them out.  I'll update the readme incase anyone else encounters this.

Thanks for the follow up!
